version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout

    runtime:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log/runtime.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    dp:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: log/datapipeline.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

loggers:
    dp:
        handlers: [dp]

root:
    handlers: [console, runtime]